# Generated by Django 5.2.17 on 2026-08-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_owner_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedUpdate',
            fields=[
                ('update_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
