# Generated by Django 5.2.17 on 2026-08-23 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_account_id_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='portal_login',
            field=models.OneToOneField(blank=True, help_text='Django staff account this admin uses to log into /staff-admin/, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Which bot admin ran /create for this account, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to='accounts.admin'),
        ),
    ]
