# Generated by Django 5.2.17 on 2026-08-23 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_account_number_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=12, unique=True)),
                ('kind', models.CharField(choices=[('transfer', 'Transfer'), ('deposit', 'External deposit')], max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('recipient', models.CharField(blank=True, help_text='Transfer: recipient account number.', max_length=64)),
                ('platform', models.CharField(blank=True, help_text='Deposit: source platform.', max_length=128)),
                ('external_ref', models.CharField(blank=True, help_text='Deposit: external reference ID.', max_length=128)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.BigIntegerField(blank=True, help_text="Admin's telegram_id at time of decision.", null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
