# Generated by Django 5.2.17 on 2026-08-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='recipient_bank',
            field=models.CharField(blank=True, help_text='Transfer: bank detected from the routing number, if known.', max_length=128),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='routing_number',
            field=models.CharField(blank=True, help_text='Transfer: recipient bank routing number.', max_length=9),
        ),
    ]
