# Generated by Django 5.2.17 on 2026-08-23 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_servicerequest_recipient_bank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs_status', models.CharField(choices=[('received', 'Received'), ('missing', 'Missing / incomplete')], default='received', max_length=10)),
                ('review_status', models.CharField(choices=[('in_review', 'In review'), ('reviewed', 'Reviewed')], default='in_review', max_length=10)),
                ('result_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('resubmit', 'Needs resubmission'), ('info_needed', 'Additional info requested')], default='pending', max_length=12)),
                ('production_status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In progress'), ('ready', 'Ready')], default='waiting', max_length=12)),
                ('shipping_status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped')], default='pending', max_length=10)),
                ('tracking_number', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
