# Generated by Django 5.2.17 on 2026-08-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_cardapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='avatar',
            field=models.CharField(choices=[('woman', 'Woman'), ('man', 'Man')], default='woman', max_length=8),
        ),
        migrations.AddField(
            model_name='admin',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='admin',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='admin',
            name='first_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='admin',
            name='last_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
