# Generated by Django 5.2.17 on 2026-08-23 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_admin_avatar_admin_contact_email_admin_contact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=5)),
                ('body', models.TextField(max_length=2000)),
                ('sent_by_admin', models.BigIntegerField(blank=True, help_text="Admin's telegram_id when sender is admin.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
