# Generated by Django 5.2.17 on 2026-08-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_portalmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Positive = credit, negative = debit.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
