# Generated by Django 5.2.17 on 2026-08-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_address_line1_user_address_line2_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='When the user opened the thread. Admin messages only.', null=True),
        ),
    ]
